FloatLayout:
    cols: 1

    Label:
        id: lbl_dolar
        text: 'Dolar:'
        pos: '-90dp', '70dp'
        color: 1, 0, 0, 1

    Label:
        id: lbl_cotacao2
        text: '?'
        pos: '60dp', '70dp'

    Label:
        id: lbl_euro
        text: 'Euro:'
        pos: '-90dp', '30dp'
        color: 1, 0, 0, 1

    Label:
        id: lbl_cotacao1
        text: '?'
        pos: '60dp', '30dp'













